development:
  adapter: postgresql
  encoding: unicode
  database: demoapp_dev
  pool: 5
  username: tibo
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: dempapp_prod
  pool: 5
  username: tibo
  password:
  host: localhost
